name: wealth_calculator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  http: ^1.6.0
  html: ^0.15.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  lottie: ^3.0.0
  flutter_native_splash: ^2.4.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  shared_preferences: ^2.2.3
  fl_chart: ^0.70.0
  logger: ^2.6.2
  easy_logger: ^0.0.2

  # Modules 
  gen:
    path: ./module/gen

flutter_native_splash:
  color: "#2196F3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - database/inventory.db
    - images/logo.png
